/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as CorrelationRouteImport } from './routes/correlation'
import { Route as DataProcessingRouteImport } from './routes/data-processing'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as InstitutionsRouteImport } from './routes/institutions'
import { Route as InstructorsRouteImport } from './routes/instructors'
import { Route as InvestigationsRouteImport } from './routes/investigations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ScoringRouteImport } from './routes/scoring'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as AcceptInviteTokenRouteImport } from './routes/accept-invite.$token'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAchievementsRouteImport } from './routes/app.achievements'
import { Route as AppAlertsRouteImport } from './routes/app.alerts'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAssessmentsRouteImport } from './routes/app.assessments'
import { Route as AppAuditLogsRouteImport } from './routes/app.audit-logs'
import { Route as AppBillingRouteImport } from './routes/app.billing'
import { Route as AppCertificatesRouteImport } from './routes/app.certificates'
import { Route as AppClosedRouteImport } from './routes/app.closed'
import { Route as AppCohortsRouteImport } from './routes/app.cohorts'
import { Route as AppDocsRouteImport } from './routes/app.docs'
import { Route as AppEvidenceRouteImport } from './routes/app.evidence'
import { Route as AppFeedbackRouteImport } from './routes/app.feedback'
import { Route as AppGraphRouteImport } from './routes/app.graph'
import { Route as AppIncidentsRouteImport } from './routes/app.incidents'
import { Route as AppInstructorRouteImport } from './routes/app.instructor'
import { Route as AppLeaderboardRouteImport } from './routes/app.leaderboard'
import { Route as AppLearningRouteImport } from './routes/app.learning'
import { Route as AppLogsRouteImport } from './routes/app.logs'
import { Route as AppMitreRouteImport } from './routes/app.mitre'
import { Route as AppNetworkRouteImport } from './routes/app.network'
import { Route as AppOrganizationsRouteImport } from './routes/app.organizations'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppScenarioBuilderRouteImport } from './routes/app.scenario-builder'
import { Route as AppScenariosRouteImport } from './routes/app.scenarios'
import { Route as AppSearchRouteImport } from './routes/app.search'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppStudentAnalyticsRouteImport } from './routes/app.student-analytics'
import { Route as AppThreatIntelRouteImport } from './routes/app.threat-intel'
import { Route as AppTimelineRouteImport } from './routes/app.timeline'
import { Route as JoinCohortTokenRouteImport } from './routes/join-cohort.$token'
import { Route as ResetPasswordTokenRouteImport } from './routes/reset-password.$token'
import { Route as VerifyEmailTokenRouteImport } from './routes/verify-email.$token'
import { Route as VerifyIdRouteImport } from './routes/verify.$id'
import { Route as AppCasesIndexRouteImport } from './routes/app.cases.index'
import { Route as AppCasesIdRouteImport } from './routes/app.cases.$id'
import { Route as AppEmailIndexRouteImport } from './routes/app.email.index'
import { Route as AppEndpointsIndexRouteImport } from './routes/app.endpoints.index'
import { Route as AppIdentityIndexRouteImport } from './routes/app.identity.index'
import { Route as AppReportsIndexRouteImport } from './routes/app.reports.index'
import { Route as AppEmailSessionIdMessageIdRouteImport } from './routes/app.email.$sessionId.$messageId'
import { Route as AppEndpointsSessionIdDeviceIdRouteImport } from './routes/app.endpoints.$sessionId.$deviceId'
import { Route as AppIdentitySessionIdIdentityIdRouteImport } from './routes/app.identity.$sessionId.$identityId'
import { Route as AppReportsSessionIdIncidentIdRouteImport } from './routes/app.reports.$sessionId.$incidentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const CorrelationRoute = CorrelationRouteImport.update({
  id: '/correlation',
  path: '/correlation',
  getParentRoute: () => rootRouteImport,
} as any)
const DataProcessingRoute = DataProcessingRouteImport.update({
  id: '/data-processing',
  path: '/data-processing',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionsRoute = InstitutionsRouteImport.update({
  id: '/institutions',
  path: '/institutions',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorsRoute = InstructorsRouteImport.update({
  id: '/instructors',
  path: '/instructors',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationsRoute = InvestigationsRouteImport.update({
  id: '/investigations',
  path: '/investigations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoringRoute = ScoringRouteImport.update({
  id: '/scoring',
  path: '/scoring',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteTokenRoute = AcceptInviteTokenRouteImport.update({
  id: '/accept-invite/$token',
  path: '/accept-invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAchievementsRoute = AppAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAssessmentsRoute = AppAssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditLogsRoute = AppAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppCertificatesRoute = AppCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => AppRoute,
} as any)
const AppClosedRoute = AppClosedRouteImport.update({
  id: '/closed',
  path: '/closed',
  getParentRoute: () => AppRoute,
} as any)
const AppCohortsRoute = AppCohortsRouteImport.update({
  id: '/cohorts',
  path: '/cohorts',
  getParentRoute: () => AppRoute,
} as any)
const AppDocsRoute = AppDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AppRoute,
} as any)
const AppEvidenceRoute = AppEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedbackRoute = AppFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AppRoute,
} as any)
const AppGraphRoute = AppGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => AppRoute,
} as any)
const AppIncidentsRoute = AppIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AppRoute,
} as any)
const AppInstructorRoute = AppInstructorRouteImport.update({
  id: '/instructor',
  path: '/instructor',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppLearningRoute = AppLearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsRoute = AppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppRoute,
} as any)
const AppMitreRoute = AppMitreRouteImport.update({
  id: '/mitre',
  path: '/mitre',
  getParentRoute: () => AppRoute,
} as any)
const AppNetworkRoute = AppNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationsRoute = AppOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppScenarioBuilderRoute = AppScenarioBuilderRouteImport.update({
  id: '/scenario-builder',
  path: '/scenario-builder',
  getParentRoute: () => AppRoute,
} as any)
const AppScenariosRoute = AppScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentAnalyticsRoute = AppStudentAnalyticsRouteImport.update({
  id: '/student-analytics',
  path: '/student-analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppThreatIntelRoute = AppThreatIntelRouteImport.update({
  id: '/threat-intel',
  path: '/threat-intel',
  getParentRoute: () => AppRoute,
} as any)
const AppTimelineRoute = AppTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AppRoute,
} as any)
const JoinCohortTokenRoute = JoinCohortTokenRouteImport.update({
  id: '/join-cohort/$token',
  path: '/join-cohort/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordTokenRoute = ResetPasswordTokenRouteImport.update({
  id: '/reset-password/$token',
  path: '/reset-password/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailTokenRoute = VerifyEmailTokenRouteImport.update({
  id: '/verify-email/$token',
  path: '/verify-email/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyIdRoute = VerifyIdRouteImport.update({
  id: '/verify/$id',
  path: '/verify/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCasesIndexRoute = AppCasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => AppRoute,
} as any)
const AppCasesIdRoute = AppCasesIdRouteImport.update({
  id: '/cases/$id',
  path: '/cases/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppEmailIndexRoute = AppEmailIndexRouteImport.update({
  id: '/email/',
  path: '/email/',
  getParentRoute: () => AppRoute,
} as any)
const AppEndpointsIndexRoute = AppEndpointsIndexRouteImport.update({
  id: '/endpoints/',
  path: '/endpoints/',
  getParentRoute: () => AppRoute,
} as any)
const AppIdentityIndexRoute = AppIdentityIndexRouteImport.update({
  id: '/identity/',
  path: '/identity/',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AppRoute,
} as any)
const AppEmailSessionIdMessageIdRoute =
  AppEmailSessionIdMessageIdRouteImport.update({
    id: '/email/$sessionId/$messageId',
    path: '/email/$sessionId/$messageId',
    getParentRoute: () => AppRoute,
  } as any)
const AppEndpointsSessionIdDeviceIdRoute =
  AppEndpointsSessionIdDeviceIdRouteImport.update({
    id: '/endpoints/$sessionId/$deviceId',
    path: '/endpoints/$sessionId/$deviceId',
    getParentRoute: () => AppRoute,
  } as any)
const AppIdentitySessionIdIdentityIdRoute =
  AppIdentitySessionIdIdentityIdRouteImport.update({
    id: '/identity/$sessionId/$identityId',
    path: '/identity/$sessionId/$identityId',
    getParentRoute: () => AppRoute,
  } as any)
const AppReportsSessionIdIncidentIdRoute =
  AppReportsSessionIdIncidentIdRouteImport.update({
    id: '/reports/$sessionId/$incidentId',
    path: '/reports/$sessionId/$incidentId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/correlation': typeof CorrelationRoute
  '/data-processing': typeof DataProcessingRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/institutions': typeof InstitutionsRoute
  '/instructors': typeof InstructorsRoute
  '/investigations': typeof InvestigationsRoute
  '/login': typeof LoginRoute
  '/platform': typeof PlatformRoute
  '/privacy': typeof PrivacyRoute
  '/scoring': typeof ScoringRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/students': typeof StudentsRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/assessments': typeof AppAssessmentsRoute
  '/app/audit-logs': typeof AppAuditLogsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/certificates': typeof AppCertificatesRoute
  '/app/closed': typeof AppClosedRoute
  '/app/cohorts': typeof AppCohortsRoute
  '/app/docs': typeof AppDocsRoute
  '/app/evidence': typeof AppEvidenceRoute
  '/app/feedback': typeof AppFeedbackRoute
  '/app/graph': typeof AppGraphRoute
  '/app/incidents': typeof AppIncidentsRoute
  '/app/instructor': typeof AppInstructorRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/learning': typeof AppLearningRoute
  '/app/logs': typeof AppLogsRoute
  '/app/mitre': typeof AppMitreRoute
  '/app/network': typeof AppNetworkRoute
  '/app/organizations': typeof AppOrganizationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/scenario-builder': typeof AppScenarioBuilderRoute
  '/app/scenarios': typeof AppScenariosRoute
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/student-analytics': typeof AppStudentAnalyticsRoute
  '/app/threat-intel': typeof AppThreatIntelRoute
  '/app/timeline': typeof AppTimelineRoute
  '/join-cohort/$token': typeof JoinCohortTokenRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/verify-email/$token': typeof VerifyEmailTokenRoute
  '/verify/$id': typeof VerifyIdRoute
  '/app/': typeof AppIndexRoute
  '/app/cases/$id': typeof AppCasesIdRoute
  '/app/cases/': typeof AppCasesIndexRoute
  '/app/email/': typeof AppEmailIndexRoute
  '/app/endpoints/': typeof AppEndpointsIndexRoute
  '/app/identity/': typeof AppIdentityIndexRoute
  '/app/reports/': typeof AppReportsIndexRoute
  '/app/email/$sessionId/$messageId': typeof AppEmailSessionIdMessageIdRoute
  '/app/endpoints/$sessionId/$deviceId': typeof AppEndpointsSessionIdDeviceIdRoute
  '/app/identity/$sessionId/$identityId': typeof AppIdentitySessionIdIdentityIdRoute
  '/app/reports/$sessionId/$incidentId': typeof AppReportsSessionIdIncidentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/correlation': typeof CorrelationRoute
  '/data-processing': typeof DataProcessingRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/institutions': typeof InstitutionsRoute
  '/instructors': typeof InstructorsRoute
  '/investigations': typeof InvestigationsRoute
  '/login': typeof LoginRoute
  '/platform': typeof PlatformRoute
  '/privacy': typeof PrivacyRoute
  '/scoring': typeof ScoringRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/students': typeof StudentsRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/assessments': typeof AppAssessmentsRoute
  '/app/audit-logs': typeof AppAuditLogsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/certificates': typeof AppCertificatesRoute
  '/app/closed': typeof AppClosedRoute
  '/app/cohorts': typeof AppCohortsRoute
  '/app/docs': typeof AppDocsRoute
  '/app/evidence': typeof AppEvidenceRoute
  '/app/feedback': typeof AppFeedbackRoute
  '/app/graph': typeof AppGraphRoute
  '/app/incidents': typeof AppIncidentsRoute
  '/app/instructor': typeof AppInstructorRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/learning': typeof AppLearningRoute
  '/app/logs': typeof AppLogsRoute
  '/app/mitre': typeof AppMitreRoute
  '/app/network': typeof AppNetworkRoute
  '/app/organizations': typeof AppOrganizationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/scenario-builder': typeof AppScenarioBuilderRoute
  '/app/scenarios': typeof AppScenariosRoute
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/student-analytics': typeof AppStudentAnalyticsRoute
  '/app/threat-intel': typeof AppThreatIntelRoute
  '/app/timeline': typeof AppTimelineRoute
  '/join-cohort/$token': typeof JoinCohortTokenRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/verify-email/$token': typeof VerifyEmailTokenRoute
  '/verify/$id': typeof VerifyIdRoute
  '/app': typeof AppIndexRoute
  '/app/cases/$id': typeof AppCasesIdRoute
  '/app/cases': typeof AppCasesIndexRoute
  '/app/email': typeof AppEmailIndexRoute
  '/app/endpoints': typeof AppEndpointsIndexRoute
  '/app/identity': typeof AppIdentityIndexRoute
  '/app/reports': typeof AppReportsIndexRoute
  '/app/email/$sessionId/$messageId': typeof AppEmailSessionIdMessageIdRoute
  '/app/endpoints/$sessionId/$deviceId': typeof AppEndpointsSessionIdDeviceIdRoute
  '/app/identity/$sessionId/$identityId': typeof AppIdentitySessionIdIdentityIdRoute
  '/app/reports/$sessionId/$incidentId': typeof AppReportsSessionIdIncidentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/correlation': typeof CorrelationRoute
  '/data-processing': typeof DataProcessingRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/institutions': typeof InstitutionsRoute
  '/instructors': typeof InstructorsRoute
  '/investigations': typeof InvestigationsRoute
  '/login': typeof LoginRoute
  '/platform': typeof PlatformRoute
  '/privacy': typeof PrivacyRoute
  '/scoring': typeof ScoringRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/students': typeof StudentsRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/assessments': typeof AppAssessmentsRoute
  '/app/audit-logs': typeof AppAuditLogsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/certificates': typeof AppCertificatesRoute
  '/app/closed': typeof AppClosedRoute
  '/app/cohorts': typeof AppCohortsRoute
  '/app/docs': typeof AppDocsRoute
  '/app/evidence': typeof AppEvidenceRoute
  '/app/feedback': typeof AppFeedbackRoute
  '/app/graph': typeof AppGraphRoute
  '/app/incidents': typeof AppIncidentsRoute
  '/app/instructor': typeof AppInstructorRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/learning': typeof AppLearningRoute
  '/app/logs': typeof AppLogsRoute
  '/app/mitre': typeof AppMitreRoute
  '/app/network': typeof AppNetworkRoute
  '/app/organizations': typeof AppOrganizationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/scenario-builder': typeof AppScenarioBuilderRoute
  '/app/scenarios': typeof AppScenariosRoute
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/student-analytics': typeof AppStudentAnalyticsRoute
  '/app/threat-intel': typeof AppThreatIntelRoute
  '/app/timeline': typeof AppTimelineRoute
  '/join-cohort/$token': typeof JoinCohortTokenRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/verify-email/$token': typeof VerifyEmailTokenRoute
  '/verify/$id': typeof VerifyIdRoute
  '/app/': typeof AppIndexRoute
  '/app/cases/$id': typeof AppCasesIdRoute
  '/app/cases/': typeof AppCasesIndexRoute
  '/app/email/': typeof AppEmailIndexRoute
  '/app/endpoints/': typeof AppEndpointsIndexRoute
  '/app/identity/': typeof AppIdentityIndexRoute
  '/app/reports/': typeof AppReportsIndexRoute
  '/app/email/$sessionId/$messageId': typeof AppEmailSessionIdMessageIdRoute
  '/app/endpoints/$sessionId/$deviceId': typeof AppEndpointsSessionIdDeviceIdRoute
  '/app/identity/$sessionId/$identityId': typeof AppIdentitySessionIdIdentityIdRoute
  '/app/reports/$sessionId/$incidentId': typeof AppReportsSessionIdIncidentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/contact'
    | '/cookies'
    | '/correlation'
    | '/data-processing'
    | '/forgot-password'
    | '/institutions'
    | '/instructors'
    | '/investigations'
    | '/login'
    | '/platform'
    | '/privacy'
    | '/scoring'
    | '/security'
    | '/signup'
    | '/students'
    | '/terms'
    | '/welcome'
    | '/accept-invite/$token'
    | '/app/achievements'
    | '/app/alerts'
    | '/app/analytics'
    | '/app/assessments'
    | '/app/audit-logs'
    | '/app/billing'
    | '/app/certificates'
    | '/app/closed'
    | '/app/cohorts'
    | '/app/docs'
    | '/app/evidence'
    | '/app/feedback'
    | '/app/graph'
    | '/app/incidents'
    | '/app/instructor'
    | '/app/leaderboard'
    | '/app/learning'
    | '/app/logs'
    | '/app/mitre'
    | '/app/network'
    | '/app/organizations'
    | '/app/profile'
    | '/app/scenario-builder'
    | '/app/scenarios'
    | '/app/search'
    | '/app/settings'
    | '/app/student-analytics'
    | '/app/threat-intel'
    | '/app/timeline'
    | '/join-cohort/$token'
    | '/reset-password/$token'
    | '/verify-email/$token'
    | '/verify/$id'
    | '/app/'
    | '/app/cases/$id'
    | '/app/cases/'
    | '/app/email/'
    | '/app/endpoints/'
    | '/app/identity/'
    | '/app/reports/'
    | '/app/email/$sessionId/$messageId'
    | '/app/endpoints/$sessionId/$deviceId'
    | '/app/identity/$sessionId/$identityId'
    | '/app/reports/$sessionId/$incidentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/cookies'
    | '/correlation'
    | '/data-processing'
    | '/forgot-password'
    | '/institutions'
    | '/instructors'
    | '/investigations'
    | '/login'
    | '/platform'
    | '/privacy'
    | '/scoring'
    | '/security'
    | '/signup'
    | '/students'
    | '/terms'
    | '/welcome'
    | '/accept-invite/$token'
    | '/app/achievements'
    | '/app/alerts'
    | '/app/analytics'
    | '/app/assessments'
    | '/app/audit-logs'
    | '/app/billing'
    | '/app/certificates'
    | '/app/closed'
    | '/app/cohorts'
    | '/app/docs'
    | '/app/evidence'
    | '/app/feedback'
    | '/app/graph'
    | '/app/incidents'
    | '/app/instructor'
    | '/app/leaderboard'
    | '/app/learning'
    | '/app/logs'
    | '/app/mitre'
    | '/app/network'
    | '/app/organizations'
    | '/app/profile'
    | '/app/scenario-builder'
    | '/app/scenarios'
    | '/app/search'
    | '/app/settings'
    | '/app/student-analytics'
    | '/app/threat-intel'
    | '/app/timeline'
    | '/join-cohort/$token'
    | '/reset-password/$token'
    | '/verify-email/$token'
    | '/verify/$id'
    | '/app'
    | '/app/cases/$id'
    | '/app/cases'
    | '/app/email'
    | '/app/endpoints'
    | '/app/identity'
    | '/app/reports'
    | '/app/email/$sessionId/$messageId'
    | '/app/endpoints/$sessionId/$deviceId'
    | '/app/identity/$sessionId/$identityId'
    | '/app/reports/$sessionId/$incidentId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/contact'
    | '/cookies'
    | '/correlation'
    | '/data-processing'
    | '/forgot-password'
    | '/institutions'
    | '/instructors'
    | '/investigations'
    | '/login'
    | '/platform'
    | '/privacy'
    | '/scoring'
    | '/security'
    | '/signup'
    | '/students'
    | '/terms'
    | '/welcome'
    | '/accept-invite/$token'
    | '/app/achievements'
    | '/app/alerts'
    | '/app/analytics'
    | '/app/assessments'
    | '/app/audit-logs'
    | '/app/billing'
    | '/app/certificates'
    | '/app/closed'
    | '/app/cohorts'
    | '/app/docs'
    | '/app/evidence'
    | '/app/feedback'
    | '/app/graph'
    | '/app/incidents'
    | '/app/instructor'
    | '/app/leaderboard'
    | '/app/learning'
    | '/app/logs'
    | '/app/mitre'
    | '/app/network'
    | '/app/organizations'
    | '/app/profile'
    | '/app/scenario-builder'
    | '/app/scenarios'
    | '/app/search'
    | '/app/settings'
    | '/app/student-analytics'
    | '/app/threat-intel'
    | '/app/timeline'
    | '/join-cohort/$token'
    | '/reset-password/$token'
    | '/verify-email/$token'
    | '/verify/$id'
    | '/app/'
    | '/app/cases/$id'
    | '/app/cases/'
    | '/app/email/'
    | '/app/endpoints/'
    | '/app/identity/'
    | '/app/reports/'
    | '/app/email/$sessionId/$messageId'
    | '/app/endpoints/$sessionId/$deviceId'
    | '/app/identity/$sessionId/$identityId'
    | '/app/reports/$sessionId/$incidentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  CorrelationRoute: typeof CorrelationRoute
  DataProcessingRoute: typeof DataProcessingRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InstitutionsRoute: typeof InstitutionsRoute
  InstructorsRoute: typeof InstructorsRoute
  InvestigationsRoute: typeof InvestigationsRoute
  LoginRoute: typeof LoginRoute
  PlatformRoute: typeof PlatformRoute
  PrivacyRoute: typeof PrivacyRoute
  ScoringRoute: typeof ScoringRoute
  SecurityRoute: typeof SecurityRoute
  SignupRoute: typeof SignupRoute
  StudentsRoute: typeof StudentsRoute
  TermsRoute: typeof TermsRoute
  WelcomeRoute: typeof WelcomeRoute
  AcceptInviteTokenRoute: typeof AcceptInviteTokenRoute
  JoinCohortTokenRoute: typeof JoinCohortTokenRoute
  ResetPasswordTokenRoute: typeof ResetPasswordTokenRoute
  VerifyEmailTokenRoute: typeof VerifyEmailTokenRoute
  VerifyIdRoute: typeof VerifyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/correlation': {
      id: '/correlation'
      path: '/correlation'
      fullPath: '/correlation'
      preLoaderRoute: typeof CorrelationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-processing': {
      id: '/data-processing'
      path: '/data-processing'
      fullPath: '/data-processing'
      preLoaderRoute: typeof DataProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutions': {
      id: '/institutions'
      path: '/institutions'
      fullPath: '/institutions'
      preLoaderRoute: typeof InstitutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructors': {
      id: '/instructors'
      path: '/instructors'
      fullPath: '/instructors'
      preLoaderRoute: typeof InstructorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigations': {
      id: '/investigations'
      path: '/investigations'
      fullPath: '/investigations'
      preLoaderRoute: typeof InvestigationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scoring': {
      id: '/scoring'
      path: '/scoring'
      fullPath: '/scoring'
      preLoaderRoute: typeof ScoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite/$token': {
      id: '/accept-invite/$token'
      path: '/accept-invite/$token'
      fullPath: '/accept-invite/$token'
      preLoaderRoute: typeof AcceptInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/achievements': {
      id: '/app/achievements'
      path: '/achievements'
      fullPath: '/app/achievements'
      preLoaderRoute: typeof AppAchievementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assessments': {
      id: '/app/assessments'
      path: '/assessments'
      fullPath: '/app/assessments'
      preLoaderRoute: typeof AppAssessmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit-logs': {
      id: '/app/audit-logs'
      path: '/audit-logs'
      fullPath: '/app/audit-logs'
      preLoaderRoute: typeof AppAuditLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/certificates': {
      id: '/app/certificates'
      path: '/certificates'
      fullPath: '/app/certificates'
      preLoaderRoute: typeof AppCertificatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/closed': {
      id: '/app/closed'
      path: '/closed'
      fullPath: '/app/closed'
      preLoaderRoute: typeof AppClosedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cohorts': {
      id: '/app/cohorts'
      path: '/cohorts'
      fullPath: '/app/cohorts'
      preLoaderRoute: typeof AppCohortsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/docs': {
      id: '/app/docs'
      path: '/docs'
      fullPath: '/app/docs'
      preLoaderRoute: typeof AppDocsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/evidence': {
      id: '/app/evidence'
      path: '/evidence'
      fullPath: '/app/evidence'
      preLoaderRoute: typeof AppEvidenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/feedback': {
      id: '/app/feedback'
      path: '/feedback'
      fullPath: '/app/feedback'
      preLoaderRoute: typeof AppFeedbackRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/graph': {
      id: '/app/graph'
      path: '/graph'
      fullPath: '/app/graph'
      preLoaderRoute: typeof AppGraphRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/incidents': {
      id: '/app/incidents'
      path: '/incidents'
      fullPath: '/app/incidents'
      preLoaderRoute: typeof AppIncidentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/instructor': {
      id: '/app/instructor'
      path: '/instructor'
      fullPath: '/app/instructor'
      preLoaderRoute: typeof AppInstructorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leaderboard': {
      id: '/app/leaderboard'
      path: '/leaderboard'
      fullPath: '/app/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/learning': {
      id: '/app/learning'
      path: '/learning'
      fullPath: '/app/learning'
      preLoaderRoute: typeof AppLearningRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/logs': {
      id: '/app/logs'
      path: '/logs'
      fullPath: '/app/logs'
      preLoaderRoute: typeof AppLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mitre': {
      id: '/app/mitre'
      path: '/mitre'
      fullPath: '/app/mitre'
      preLoaderRoute: typeof AppMitreRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/network': {
      id: '/app/network'
      path: '/network'
      fullPath: '/app/network'
      preLoaderRoute: typeof AppNetworkRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/organizations': {
      id: '/app/organizations'
      path: '/organizations'
      fullPath: '/app/organizations'
      preLoaderRoute: typeof AppOrganizationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/scenario-builder': {
      id: '/app/scenario-builder'
      path: '/scenario-builder'
      fullPath: '/app/scenario-builder'
      preLoaderRoute: typeof AppScenarioBuilderRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/scenarios': {
      id: '/app/scenarios'
      path: '/scenarios'
      fullPath: '/app/scenarios'
      preLoaderRoute: typeof AppScenariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/search': {
      id: '/app/search'
      path: '/search'
      fullPath: '/app/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/student-analytics': {
      id: '/app/student-analytics'
      path: '/student-analytics'
      fullPath: '/app/student-analytics'
      preLoaderRoute: typeof AppStudentAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/threat-intel': {
      id: '/app/threat-intel'
      path: '/threat-intel'
      fullPath: '/app/threat-intel'
      preLoaderRoute: typeof AppThreatIntelRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/timeline': {
      id: '/app/timeline'
      path: '/timeline'
      fullPath: '/app/timeline'
      preLoaderRoute: typeof AppTimelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/join-cohort/$token': {
      id: '/join-cohort/$token'
      path: '/join-cohort/$token'
      fullPath: '/join-cohort/$token'
      preLoaderRoute: typeof JoinCohortTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/$token': {
      id: '/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/reset-password/$token'
      preLoaderRoute: typeof ResetPasswordTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email/$token': {
      id: '/verify-email/$token'
      path: '/verify-email/$token'
      fullPath: '/verify-email/$token'
      preLoaderRoute: typeof VerifyEmailTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$id': {
      id: '/verify/$id'
      path: '/verify/$id'
      fullPath: '/verify/$id'
      preLoaderRoute: typeof VerifyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/cases/': {
      id: '/app/cases/'
      path: '/cases'
      fullPath: '/app/cases/'
      preLoaderRoute: typeof AppCasesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cases/$id': {
      id: '/app/cases/$id'
      path: '/cases/$id'
      fullPath: '/app/cases/$id'
      preLoaderRoute: typeof AppCasesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/email/': {
      id: '/app/email/'
      path: '/email'
      fullPath: '/app/email/'
      preLoaderRoute: typeof AppEmailIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/endpoints/': {
      id: '/app/endpoints/'
      path: '/endpoints'
      fullPath: '/app/endpoints/'
      preLoaderRoute: typeof AppEndpointsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/identity/': {
      id: '/app/identity/'
      path: '/identity'
      fullPath: '/app/identity/'
      preLoaderRoute: typeof AppIdentityIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports/': {
      id: '/app/reports/'
      path: '/reports'
      fullPath: '/app/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/email/$sessionId/$messageId': {
      id: '/app/email/$sessionId/$messageId'
      path: '/email/$sessionId/$messageId'
      fullPath: '/app/email/$sessionId/$messageId'
      preLoaderRoute: typeof AppEmailSessionIdMessageIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/endpoints/$sessionId/$deviceId': {
      id: '/app/endpoints/$sessionId/$deviceId'
      path: '/endpoints/$sessionId/$deviceId'
      fullPath: '/app/endpoints/$sessionId/$deviceId'
      preLoaderRoute: typeof AppEndpointsSessionIdDeviceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/identity/$sessionId/$identityId': {
      id: '/app/identity/$sessionId/$identityId'
      path: '/identity/$sessionId/$identityId'
      fullPath: '/app/identity/$sessionId/$identityId'
      preLoaderRoute: typeof AppIdentitySessionIdIdentityIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports/$sessionId/$incidentId': {
      id: '/app/reports/$sessionId/$incidentId'
      path: '/reports/$sessionId/$incidentId'
      fullPath: '/app/reports/$sessionId/$incidentId'
      preLoaderRoute: typeof AppReportsSessionIdIncidentIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAchievementsRoute: typeof AppAchievementsRoute
  AppAlertsRoute: typeof AppAlertsRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAssessmentsRoute: typeof AppAssessmentsRoute
  AppAuditLogsRoute: typeof AppAuditLogsRoute
  AppBillingRoute: typeof AppBillingRoute
  AppCertificatesRoute: typeof AppCertificatesRoute
  AppClosedRoute: typeof AppClosedRoute
  AppCohortsRoute: typeof AppCohortsRoute
  AppDocsRoute: typeof AppDocsRoute
  AppEvidenceRoute: typeof AppEvidenceRoute
  AppFeedbackRoute: typeof AppFeedbackRoute
  AppGraphRoute: typeof AppGraphRoute
  AppIncidentsRoute: typeof AppIncidentsRoute
  AppInstructorRoute: typeof AppInstructorRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppLearningRoute: typeof AppLearningRoute
  AppLogsRoute: typeof AppLogsRoute
  AppMitreRoute: typeof AppMitreRoute
  AppNetworkRoute: typeof AppNetworkRoute
  AppOrganizationsRoute: typeof AppOrganizationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppScenarioBuilderRoute: typeof AppScenarioBuilderRoute
  AppScenariosRoute: typeof AppScenariosRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStudentAnalyticsRoute: typeof AppStudentAnalyticsRoute
  AppThreatIntelRoute: typeof AppThreatIntelRoute
  AppTimelineRoute: typeof AppTimelineRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCasesIdRoute: typeof AppCasesIdRoute
  AppCasesIndexRoute: typeof AppCasesIndexRoute
  AppEmailIndexRoute: typeof AppEmailIndexRoute
  AppEndpointsIndexRoute: typeof AppEndpointsIndexRoute
  AppIdentityIndexRoute: typeof AppIdentityIndexRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
  AppEmailSessionIdMessageIdRoute: typeof AppEmailSessionIdMessageIdRoute
  AppEndpointsSessionIdDeviceIdRoute: typeof AppEndpointsSessionIdDeviceIdRoute
  AppIdentitySessionIdIdentityIdRoute: typeof AppIdentitySessionIdIdentityIdRoute
  AppReportsSessionIdIncidentIdRoute: typeof AppReportsSessionIdIncidentIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAchievementsRoute: AppAchievementsRoute,
  AppAlertsRoute: AppAlertsRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAssessmentsRoute: AppAssessmentsRoute,
  AppAuditLogsRoute: AppAuditLogsRoute,
  AppBillingRoute: AppBillingRoute,
  AppCertificatesRoute: AppCertificatesRoute,
  AppClosedRoute: AppClosedRoute,
  AppCohortsRoute: AppCohortsRoute,
  AppDocsRoute: AppDocsRoute,
  AppEvidenceRoute: AppEvidenceRoute,
  AppFeedbackRoute: AppFeedbackRoute,
  AppGraphRoute: AppGraphRoute,
  AppIncidentsRoute: AppIncidentsRoute,
  AppInstructorRoute: AppInstructorRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppLearningRoute: AppLearningRoute,
  AppLogsRoute: AppLogsRoute,
  AppMitreRoute: AppMitreRoute,
  AppNetworkRoute: AppNetworkRoute,
  AppOrganizationsRoute: AppOrganizationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppScenarioBuilderRoute: AppScenarioBuilderRoute,
  AppScenariosRoute: AppScenariosRoute,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStudentAnalyticsRoute: AppStudentAnalyticsRoute,
  AppThreatIntelRoute: AppThreatIntelRoute,
  AppTimelineRoute: AppTimelineRoute,
  AppIndexRoute: AppIndexRoute,
  AppCasesIdRoute: AppCasesIdRoute,
  AppCasesIndexRoute: AppCasesIndexRoute,
  AppEmailIndexRoute: AppEmailIndexRoute,
  AppEndpointsIndexRoute: AppEndpointsIndexRoute,
  AppIdentityIndexRoute: AppIdentityIndexRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
  AppEmailSessionIdMessageIdRoute: AppEmailSessionIdMessageIdRoute,
  AppEndpointsSessionIdDeviceIdRoute: AppEndpointsSessionIdDeviceIdRoute,
  AppIdentitySessionIdIdentityIdRoute: AppIdentitySessionIdIdentityIdRoute,
  AppReportsSessionIdIncidentIdRoute: AppReportsSessionIdIncidentIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  CorrelationRoute: CorrelationRoute,
  DataProcessingRoute: DataProcessingRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InstitutionsRoute: InstitutionsRoute,
  InstructorsRoute: InstructorsRoute,
  InvestigationsRoute: InvestigationsRoute,
  LoginRoute: LoginRoute,
  PlatformRoute: PlatformRoute,
  PrivacyRoute: PrivacyRoute,
  ScoringRoute: ScoringRoute,
  SecurityRoute: SecurityRoute,
  SignupRoute: SignupRoute,
  StudentsRoute: StudentsRoute,
  TermsRoute: TermsRoute,
  WelcomeRoute: WelcomeRoute,
  AcceptInviteTokenRoute: AcceptInviteTokenRoute,
  JoinCohortTokenRoute: JoinCohortTokenRoute,
  ResetPasswordTokenRoute: ResetPasswordTokenRoute,
  VerifyEmailTokenRoute: VerifyEmailTokenRoute,
  VerifyIdRoute: VerifyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
