import type { AuditLogsService } from "./audit-logs-service";

const logs = [
  {
    ts: "02:11:04",
    actor: "john.doe",
    action: "evidence.collect",
    target: "EVD-9014",
    ctx: "INV-3181",
    ip: "10.14.2.66",
    userAgent: "Chrome 128 · Windows",
    organization: "Contoso Global SOC",
    result: "success" as const,
  },
  {
    ts: "02:04:51",
    actor: "jonas.weber",
    action: "assessment.grade",
    target: "AS-113",
    ctx: "42 submissions",
    ip: "10.14.2.9",
    userAgent: "Chrome 128 · macOS",
    organization: "Contoso Global SOC",
    result: "success" as const,
  },
  {
    ts: "01:58:12",
    actor: "system",
    action: "scenario.randomize",
    target: "SC-081",
    ctx: "seed rotated",
    ip: "—",
    userAgent: "internal-scheduler",
    organization: "Contoso Global SOC",
    result: "success" as const,
  },
  {
    ts: "01:44:30",
    actor: "priya.nair",
    action: "case.conclude",
    target: "INV-3177",
    ctx: "verdict accepted",
    ip: "10.14.7.4",
    userAgent: "Safari 17 · macOS",
    organization: "Contoso Global SOC",
    result: "success" as const,
  },
  {
    ts: "01:31:07",
    actor: "admin",
    action: "role.grant",
    target: "marcus.chen",
    ctx: "instructor",
    ip: "10.14.1.2",
    userAgent: "Chrome 128 · Windows",
    organization: "Contoso Global SOC",
    result: "success" as const,
  },
  {
    ts: "01:12:45",
    actor: "amelia.ward",
    action: "hint.reveal",
    target: "SC-079",
    ctx: "−5% score",
    ip: "10.22.4.18",
    userAgent: "Edge 128 · Windows",
    organization: "Contoso Global SOC",
    result: "success" as const,
  },
  {
    ts: "00:58:22",
    actor: "unknown",
    action: "auth.login",
    target: "d.holt",
    ctx: "3rd failed attempt",
    ip: "185.220.101.44",
    userAgent: "curl/8.4",
    organization: "Contoso Global SOC",
    result: "failure" as const,
  },
];

const categories = [
  { label: "Investigation", value: "2,914", meter: 70 },
  { label: "Grading", value: "612", meter: 15 },
  { label: "Authentication", value: "520", meter: 12 },
  { label: "Administration", value: "136", meter: 3 },
];

export const mockAuditLogsService: AuditLogsService = {
  listEntries: () => Promise.resolve(logs),
  getStats: () =>
    Promise.resolve({
      eventsLast24h: 4182,
      adminActions: 36,
      gradingOverrides: 4,
      retentionDays: 400,
    }),
  listCategories: () => Promise.resolve(categories),
};
